image: rust

stages:
  - test
  - publish

test:
  stage: test
  script: 
    - cargo install -f cargo-tarpaulin
    - cargo tarpaulin

publish:
  stage: publish
  script: 
    - cargo login $CARGO_TOKEN
    - cargo publish
  only:
    - tags
