[package]
name = "rs-blocks-derive"
version = "0.1.0"
authors = ["Lewis Belcher <belcher_lewis@protonmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
# rs-blocks = { path = "../" }
quote = "1.0"
syn = "1.0"
